#pragma once

#include <iostream>
#include <assert.h>
#include <fstream>
#include <string>
#include <vector>
#include <sys/stat.h>

#include "buffer.h"


#ifndef DATA_DIR
// default path for storage when processing data generated by the program
// seperate from input for cleaner space
#define DATA_DIR "./programdata/"
#endif

namespace structure{

    class CSV{
        std::string filepath;
        std::ifstream is;
        std::ofstream os;

        std::string bts(BufferData);
        std::string bts(BufferS);

        public:
            CSV(std::string filename){
                filepath = DATA_DIR + filename;
            }

            void write(BufferData);
            void writeAll(std::vector<BufferData>);
            void close(){ is.close(); os.close();}

    };

    class LenCSV{
        std::string filepath;
        std::ifstream is;
        std::ofstream os;

        std::string bts(BufferData);
        std::string bts(BufferS);

        public:
            LenCSV(std::string filename){
                filepath = DATA_DIR + filename;
            }

            void write(BufferData);
            void writeAll(std::vector<BufferData>);
            void close(){ is.close(); os.close();}
    };
    class SortedIndex{
    };
}