#pragma once

#include <iostream>
#include <assert.h>
#include <fstream>
#include <string>
#include <vector>
#include <sys/stat.h>

#include "buffer.h"


#ifndef DATA_DIR
// default path for storage when processing data generated by the program
// seperate from input for cleaner space
#define DATA_DIR "./programdata/"
#endif

namespace structure{

    class DataSystem{
        protected:
            std::string filepath;
            std::ifstream is;
            std::ofstream os;

            virtual std::string bts(BufferData);
            virtual std::string bts(BufferS) = 0;

        public:
            virtual void writeHeader(BufferS);
            virtual void write(BufferData);
            virtual void writeAll(std::vector<BufferData>);
            void close(){ is.close(); os.close();}

    };

    class CSV : public DataSystem{
        std::string bts(BufferS) override;
        public:
            CSV(std::string filename){
                filepath = DATA_DIR + filename+"."+FILEEXT_CSV;
            }
    };

    class LenCSV : public DataSystem{

        std::string bts(BufferS) override;
        
        public:
            LenCSV(std::string filename){
                filepath = DATA_DIR + filename+"."+FILEEXT_LEN_CSV;
            }
    };


    class SortedIndex : public DataSystem{
        std::string indexFile;
        std::ofstream indexStream;
        protected:
            std::string bts(BufferS) override;

        public:
        SortedIndex(std::string filename){
                filepath = DATA_DIR + filename+"."+FILEEXT_INDEX_SORTED_DATA;
                indexFile = DATA_DIR + filename+"."+FILEEXT_INDEX_SORTED_INDEX;
        }
            virtual void writeHeader(BufferS) override;
            void write(BufferData) override;
            void writeAll(std::vector<BufferData>)override;
    };
}